version: "3.8"

services:
  api:
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/app
      - SPRING_DATASOURCE_USERNAME=animalia
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_PROFILE_ACTIVE=prod
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=animalia
      - POSTGRES_PASSWORD=87654321
      - POSTGRES_DB=app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U animalia"]
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: postgresql-spring
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-spring
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
